# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_srcIP', models.CharField(max_length=64)),
                ('db_destIP', models.CharField(max_length=250)),
                ('db_summary', models.CharField(max_length=500)),
            ],
        ),
    ]
