# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftIt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetdetails',
            name='db_destPort',
            field=models.IntegerField(default='555'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packetdetails',
            name='db_flags',
            field=models.CharField(default='SA', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packetdetails',
            name='db_payload',
            field=models.CharField(default='hello', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packetdetails',
            name='db_protocol',
            field=models.CharField(default='TCP', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packetdetails',
            name='db_srcPort',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packetdetails',
            name='db_ttlValue',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
