# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftIt', '0003_auto_20170821_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetdetails',
            name='db_srcPort',
        ),
    ]
